[project]
name = "parental-control"
version = "0.1.0"
description = "A parental control application"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.27.6",
    "icoextract>=0.1.6",
    "pillow>=11.1.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
